import test from 'node:test';
import assert from 'node:assert/strict';
import { createBusiness, createClause, validateBusiness, updateField, updateFieldScope, projectDocument, createTemplate, applyTemplate, duplicateBusiness, createGenerationSnapshot } from '../src/domain/documents.mjs';
function ready() { const b=createBusiness('出口业务');b.fields={lcNumber:'',seller:'SELLER',buyer:'BUYER',invoiceNumber:'INV-001',invoiceDate:'2026-09-26'};b.confirmedFields=['seller','buyer','invoiceNumber','invoiceDate'];return b; }
test('无信用证也可完成手动制单',()=>assert.deepEqual(validateBusiness(ready()),[]));
test('发票专属缺失编号不阻止装箱单',()=>{const b=ready();b.clauses.push(createClause({name:'保单编号',scope:['invoice'],confirmed:true}));assert.equal(validateBusiness(b,['packingList']).length,0);assert.equal(validateBusiness(b,['invoice'])[0].code,'MISSING_CLAUSE_VALUE');});
test('签字要求仅进入操作清单且遵守单据范围',()=>{const b=ready();b.clauses.push(createClause({name:'签字',value:'发票需签字',type:'operation',scope:['invoice']}));assert.equal(projectDocument(b,'invoice').printedClauses.length,0);assert.equal(projectDocument(b,'invoice').checklist.length,1);assert.equal(projectDocument(b,'packingList').checklist.length,0);});
test('编辑撤销对应确认但不撤销无关字段',()=>{const b=updateField(ready(),'invoiceNumber','INV-002');assert.ok(!b.confirmedFields.includes('invoiceNumber'));assert.ok(b.confirmedFields.includes('seller'));assert.equal(b.revision,2);});
test('相同值不增加版本或撤销确认',()=>assert.deepEqual(updateField(ready(),'invoiceNumber','INV-001').confirmedFields,ready().confirmedFields));
test('模板不保留实际编号和交易数据',()=>{const b=ready();b.clauses.push(createClause({name:'PI',value:'SECRET-001'}));const t=createTemplate(b,'常用');assert.equal(t.clauses[0].value,'');assert.ok(!JSON.stringify(t).includes('SECRET-001'));assert.equal(t.fields,undefined);});
test('模板同名字段有范围冲突时禁止部分应用',()=>{const original=ready();original.clauses.push(createClause({name:'PI',value:'NEW',scope:['invoice']}));const source=ready();source.clauses.push(createClause({name:'PI',scope:['packingList']}));source.clauses.push(createClause({name:'合同'}));const result=applyTemplate(original,createTemplate(source,'模板'));assert.equal(result.conflicts.length,1);assert.deepEqual(result.business,original);});
test('模板相同字段保留现有业务值',()=>{const b=ready();b.clauses.push(createClause({name:'PI',value:'NEW'}));const result=applyTemplate(b,createTemplate(b,'模板'));assert.equal(result.conflicts.length,0);assert.equal(result.business.clauses[0].value,'NEW');});
test('业务复制清空编号并保留待确认交易方',()=>{const b=ready();b.clauses.push(createClause({name:'PI',value:'OLD',confirmed:true}));const duplicate=duplicateBusiness(b);assert.notEqual(duplicate.id,b.id);assert.equal(duplicate.fields.invoiceNumber,'');assert.equal(duplicate.fields.seller,'SELLER');assert.equal(duplicate.clauses[0].value,'');assert.equal(duplicate.clauses[0].confirmed,false);assert.deepEqual(duplicate.confirmedFields,[]);});
test('生成快照不随源业务和模板修改',()=>{const b=ready(),t=createTemplate(b,'标准');const s=createGenerationSnapshot(b,t);b.fields.seller='CHANGED';t.name='CHANGED';assert.equal(s.documents[0].fields.seller,'SELLER');assert.equal(s.template.name,'标准');});
test('未确认信息阻止快照生成',()=>{const b=ready();b.confirmedFields=[];assert.throws(()=>createGenerationSnapshot(b,createTemplate(b,'标准')),/未完成检查/);});
test('空适用范围和未知单据不能静默忽略',()=>{const b=ready();b.clauses.push(createClause({name:'PI',scope:[]}));assert.equal(validateBusiness(b)[0].code,'UNKNOWN_SCOPE');assert.throws(()=>projectDocument(b,'unknown'));});
test('逐项选择保留单据并阻止排除必需表头字段',()=>{let b=updateFieldScope(ready(),'lcNumber',['invoice']);b.fields.lcNumber='LC-001';assert.equal(projectDocument(b,'invoice').fields.lcNumber,'LC-001');assert.equal(projectDocument(b,'packingList').fields.lcNumber,'');b=updateFieldScope(b,'seller',['invoice']);assert.ok(validateBusiness(b,['packingList']).some(x=>x.code==='MISSING_FIELD_SCOPE'));assert.equal(projectDocument(b,'packingList').fields.seller,'');});
test('旧业务缺少字段范围时仍按两种单据输出',()=>{const b=ready();delete b.fieldScopes;assert.equal(projectDocument(b,'packingList').fields.seller,'SELLER');assert.equal(validateBusiness(b,['packingList']).length,0);});
test('填写的可选信用证号若要输出也必须核对',()=>{const b=ready();b.fields.lcNumber='LC-001';assert.ok(validateBusiness(b,['invoice']).some(x=>x.code==='UNCONFIRMED_FIELD'&&x.path==='fields.lcNumber'));b.fieldScopes.lcNumber=[];assert.equal(validateBusiness(b,['invoice']).length,0);});
