const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<i data-lucide="${n}"></i>`;
const blank=()=>({name:'未命名业务',lc:'',seller:'',buyer:'',invoice:'',date:'',confirmed:false,clauses:[],file:''});
const demo=()=>({name:'秋季纺织品出口 · 示例业务',lc:'DEMO-LC-260926',seller:'DEMO TEXTILES CO., LTD.\n88 SAMPLE ROAD, SHANGHAI, CHINA',buyer:'EXAMPLE TRADING LTD.\n12 EXAMPLE STREET, LONDON, UK',invoice:'INV-DEMO-026',date:'2026-09-26',confirmed:false,file:'信用证示例.pdf',clauses:[{name:'PI 编号',value:'PI-DEMO-001',scope:'全部单据',required:true,type:'编号字段',source:'47A · 示例条款 01'},{name:'保单编号',value:'',scope:'发票',required:true,type:'编号字段',source:'46A · 示例条款 02'},{name:'签字要求',value:'发票需签字。',scope:'发票',required:false,type:'操作要求',source:'46A · 示例条款 03'}]});
let state={business:demo(),templates:[{name:'标准出口单据',version:1,clauses:[]}],selected:'标准出口单据',doc:'发票'};
try{const raw=localStorage.getItem('lc-design-v1');if(raw){const p=JSON.parse(raw);if(p.business&&Array.isArray(p.templates))state=p;}}catch(e){console.warn('本地草稿未能读取',e);}
let page='home',step=1,source='47A',toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3000);}
function save(){try{localStorage.setItem('lc-design-v1',JSON.stringify(state));$('#saved').textContent='已保存到当前浏览器 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}catch(e){$('#saved').textContent='保存失败，请保留当前页面';toast('浏览器存储不可用，草稿未能保存');}}
const title={home:'业务总览',work:'制单工作台',templates:'模板中心',preview:'预览与检查'};
function go(p,s){page=p;if(s!==undefined)step=s;render();window.scrollTo(0,0);}
function heading(k,t,p,actions=''){return `<div class="topline"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p style="margin:0">${p}</p></div><div class="actions">${actions}</div></div>`;}
function issues(){const b=state.business,r=[];for(const [key,label]of [['seller','卖方名称及地址'],['buyer','买方名称及地址'],['invoice','发票编号']])if(!b[key].trim())r.push({text:'补充'+label,step:1});for(const c of b.clauses){if(!c.name.trim())r.push({text:'填写额外条款名称',step:2});if(c.required&&!c.value.trim())r.push({text:'补充'+(c.name||'条款内容'),step:2});}if(!b.confirmed)r.push({text:'确认基础信息及交易方对应关系',step:1});return r;}
function render(){ $('#crumb').textContent=title[page];$('#nav').innerHTML=Object.entries(title).map(([k,v],i)=>`<button class="${page===k?'active':''}" onclick="go('${k}')">${icon(['layout-dashboard','file-pen-line','files','scan-eye'][i])}${v}</button>`).join('');$('#app').innerHTML=({home:home,work:work,templates:templates,preview:preview}[page])();lucide.createIcons();}
function home(){const b=state.business;return heading('DOCUMENT WORKSPACE','每一份单据，从这里开始。','将信用证、业务信息与单据模板放在同一处。',`<button class="primary" onclick="newBusiness()">${icon('plus')}新建业务</button>`)+`<div class="metrics"><div class="metric"><span class="muted">当前业务</span><strong>01</strong></div><div class="metric"><span class="muted">待处理检查项</span><strong>${issues().length.toString().padStart(2,'0')}</strong></div><div class="metric"><span class="muted">可用模板</span><strong>${state.templates.length.toString().padStart(2,'0')}</strong></div><div style="margin-left:auto;max-width:230px" class="muted">先核对，再生成。<br><br>从信用证提取的信息与手动补充内容，统一保存在业务草稿中。</div></div><div class="toolbar"><h2>当前业务</h2><button onclick="loadDemo()">载入示例业务</button></div><div class="panel"><table><thead><tr><th>业务名称</th><th>信用证号</th><th>状态</th><th></th></tr></thead><tbody><tr><td><strong>${esc(b.name)}</strong><span class="muted">${b.file?'文件录入':'手动录入'} · 当前浏览器草稿</span></td><td>${esc(b.lc)||'尚未填写'}</td><td><span class="pill warn">${issues().length?'待核对':'可预览'}</span></td><td><button onclick="go('work',1)">继续制单 ${icon('arrow-right')}</button></td></tr></tbody></table></div><div class="split" style="margin-top:28px"><div class="panel"><div class="eyebrow">01 / 从文件开始</div><h2>已有信用证？</h2><p>选择 PDF 或图片，进入原文与字段并排核对的工作台。</p><button onclick="go('work',0)">${icon('upload')}选择信用证</button></div><div class="panel"><div class="eyebrow">02 / 从资料开始</div><h2>直接填写，同样完整。</h2><p>填写基础抬头，补充 PI、保单编号及其他要求，再选择模板。</p><button onclick="go('work',1)">${icon('pencil-line')}填写当前业务</button></div></div>`;}
function newBusiness(){if(!confirm('新建业务会替换当前浏览器中的演示草稿。是否继续？'))return;state.business=blank();save();go('work',0);}
function loadDemo(){if(!confirm('载入示例将替换当前演示草稿，是否继续？'))return;state.business=demo();save();go('work',1);}
function field(key,label,multi=false){return `<label>${label}${multi?`<textarea oninput="setField('${key}',this.value)">${esc(state.business[key])}</textarea>`:`<input value="${esc(state.business[key])}" oninput="setField('${key}',this.value)" ${key==='date'?'type="date"':''}>`}</label>`;}
function setField(k,v){state.business[k]=v;state.business.confirmed=false;const el=$('#confirmed');if(el)el.checked=false;save();}
function work(){let content='';if(step===0)content=`<div class="split"><section class="panel"><h2>上传信用证</h2><p>支持 PDF、JPG、PNG。原型仅记录文件名称。</p><div class="upload">${icon('file-up')}<h3>选择信用证正本或修改证</h3><label style="margin:18px auto;max-width:300px"><input type="file" accept=".pdf,.jpg,.jpeg,.png" onchange="selectFile(this)"></label><span class="muted">演示限制：单文件不超过 20 MB</span></div><p id="fileStatus">${esc(state.business.file)||'尚未选择文件'}</p><button onclick="loadDemo()">载入示例识别结果</button></section><section class="panel"><div class="eyebrow">MANUAL ENTRY</div><h2>也可以直接填写</h2><p>无需文件即可开始。已有的编号、客户信息和条款可逐项录入。</p><button class="primary" onclick="go('work',1)">进入手动填写 ${icon('arrow-right')}</button><div style="margin-top:40px;border-top:1px solid var(--line);padding-top:20px"><h3>文件识别交互约定</h3><p>识别中显示处理进度；失败时保留文件并提供重试和手动录入入口。修改证产生的差异需逐项确认。</p></div></section></div>`;
if(step===1)content=`<div class="split"><section class="source"><div class="sectionbar"><span class="muted">${state.business.file?'原文参考 · 示例摘录':'手动录入说明'}</span><span class="pill">${state.business.file?'演示数据':'无需文件'}</span></div><article class="sheet"><h3>DOCUMENTARY CREDIT</h3>${state.business.file?`<div class="sourceblock"><b>:20: DOCUMENTARY CREDIT NUMBER</b><br>DEMO-LC-260926</div><div class="sourceblock"><b>:50: APPLICANT</b><br>EXAMPLE TRADING LTD.<br>12 EXAMPLE STREET, LONDON, UK</div><div class="sourceblock"><b>:59: BENEFICIARY</b><br>DEMO TEXTILES CO., LTD.<br>88 SAMPLE ROAD, SHANGHAI, CHINA</div><div class="sourceblock selected"><b>核对提示</b><br>申请人、受益人与买卖方的对应关系需要确认。此处为示例摘录，并非所选文件的识别结果。</div>`:`<div class="sourceblock">在右侧填写交易双方和发票信息。<br><br>下一步可以添加 PI 编号、保单编号、固定声明或操作要求。<br><br>所有草稿仅保存在此浏览器。</div>`}</article></section><section class="panel"><div class="sectionbar"><h2>基础信息</h2><span class="pill warn">人工核对</span></div>${field('name','业务名称')}<div class="fieldgrid">${field('lc','信用证号（无信用证时可留空）')}${field('invoice','发票编号 *')}</div>${field('seller','卖方名称及地址 *',true)}${field('buyer','买方名称及地址 *',true)}${field('date','发票日期')}<label class="check"><input type="checkbox" id="confirmed" ${state.business.confirmed?'checked':''} onchange="state.business.confirmed=this.checked;save()">我已核对上述信息及交易方对应关系</label></section></div>`;
if(step===2)content=`<div class="split"><section class="source"><div class="sectionbar"><span>条款来源</span><div class="actions"><button onclick="source='46A';render()">46A</button><button onclick="source='47A';render()">47A</button></div></div><article class="sheet"><h3>${source==='47A'?'ADDITIONAL CONDITIONS':'DOCUMENTS REQUIRED'}</h3><div class="sourceblock selected">${source==='47A'?'01. ALL DOCUMENTS MUST INDICATE PI NO. PI-DEMO-001.':'02. COMMERCIAL INVOICE MUST INDICATE THE INSURANCE POLICY NUMBER.<br><br>03. COMMERCIAL INVOICE MUST BE SIGNED.'}</div><p style="font-family:inherit">示例摘录，仅用于演示字段与来源之间的交互。</p></article><p style="margin-top:18px">缺少编号值时保留待填项，不能将原文要求误当成实际编号。</p></section><section class="panel"><div class="sectionbar"><h2>额外条款与自定义内容</h2><button onclick="addClause()">${icon('plus')}新增条款</button></div><div class="warning">编号和固定文字进入单据；签字、份数等操作要求进入检查清单。</div>${state.business.clauses.length?state.business.clauses.map((c,i)=>`<div class="clause"><div class="clausehead"><span class="pill ${c.required&&!c.value?'warn':''}">${c.required&&!c.value?'待补充':'已录入'}</span><button aria-label="删除条款 ${i+1}" onclick="removeClause(${i})">${icon('trash-2')}</button></div><div class="fieldgrid"><label>字段 / 条款名称<input value="${esc(c.name)}" oninput="setClause(${i},'name',this.value)"></label><label>类型<select onchange="setClause(${i},'type',this.value)">${['编号字段','固定文字','操作要求'].map(x=>`<option ${c.type===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>内容 / 编号值<input placeholder="请填写，系统不会猜填" value="${esc(c.value)}" oninput="setClause(${i},'value',this.value)"></label><div class="fieldgrid"><label>适用单据<select onchange="setClause(${i},'scope',this.value)">${['全部单据','发票','装箱单'].map(x=>`<option ${c.scope===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="check"><input type="checkbox" ${c.required?'checked':''} onchange="setClause(${i},'required',this.checked)">必填项</label></div><div class="muted">来源：${esc(c.source)}</div></div>`).join(''):'<div class="empty">尚无额外条款。可添加 PI 编号、保单编号或固定文字。</div>'}</section></div>`;
return heading('PREPARE / REVIEW',esc(state.business.name),'基础字段与额外要求，在同一份业务中核对。')+`<div class="steps">${['资料录入','基础信息','额外条款'].map((s,i)=>`<button class="${step===i?'active':''}" onclick="go('work',${i})">0${i+1} ${s}</button>`).join('')}</div>`+content+`<div class="bottom"><span class="muted">草稿在输入时自动保存</span><div class="actions"><button onclick="go('home')">返回总览</button><button class="primary" onclick="go('${step===2?'preview':'work'}',${step+1})">${step===2?'选择模板并预览':'下一步'} ${icon('arrow-right')}</button></div></div>`;}
function selectFile(input){const f=input.files[0];if(!f)return;if(!/\.(pdf|jpe?g|png)$/i.test(f.name)||f.size>20*1024*1024){toast('请选择 20 MB 以内的 PDF、JPG 或 PNG');input.value='';return;}state.business.file=f.name;save();$('#fileStatus').textContent='已选择：'+f.name+'（仅记录名称，尚未识别）';}
function addClause(){state.business.clauses.push({name:'',value:'',scope:'发票',required:true,type:'编号字段',source:'用户新增'});save();render();}
function setClause(i,k,v){state.business.clauses[i][k]=v;save();}
function removeClause(i){if(!confirm('删除这条额外条款？'))return;state.business.clauses.splice(i,1);save();render();}
function templates(){return heading('TEMPLATE LIBRARY','让好用的格式，重复使用。','模板保存字段结构与适用范围，每笔业务填写自己的编号。',`<button class="primary" onclick="openTemplateDialog()">${icon('plus')}从当前业务保存模板</button>`)+`<div class="panel">${state.templates.map((t,i)=>`<article class="template"><div class="miniature">COMMERCIAL<br>INVOICE<hr>SELLER<hr>BUYER<hr>REFERENCE</div><div class="detail"><h2>${esc(t.name)}</h2><p>发票 / 装箱单 · ${t.clauses.length} 个自定义栏目</p><span class="pill">版本 ${t.version}</span> <span class="muted">编号值不会跨业务复用</span></div><button onclick="useTemplate(${i})">使用模板 ${icon('arrow-right')}</button></article>`).join('')}</div><div class="warning" style="margin-top:22px">当前原型演示字段预设的保存和应用；Word / Excel 版式上传、占位符映射与版本管理将在正式开发中实现。</div>`;}
function openTemplateDialog(){$('#templateName').value='';$('#dialog').showModal();}
$('#dialogForm').onsubmit=e=>{e.preventDefault();const name=$('#templateName').value.trim();if(!name)return;if(state.templates.some(t=>t.name===name)){toast('模板名称已存在，请换一个名称');return;}state.templates.push({name,version:1,clauses:state.business.clauses.filter(c=>c.name.trim()).map(c=>({...c,value:'',source:'模板预设'}))});state.selected=name;save();$('#dialog').close();go('templates');toast('模板已保存，业务值已清空');};
function useTemplate(i){const t=state.templates[i];state.selected=t.name;let count=0;for(const c of t.clauses){if(!state.business.clauses.some(x=>x.name===c.name)){state.business.clauses.push({...c,value:''});count++;}}save();go('preview');toast(`已应用模板，新增 ${count} 个待填写栏目；同名字段保留当前业务值`);}
function preview(){const b=state.business,list=issues(),cs=b.clauses.filter(c=>c.scope==='全部单据'||c.scope===state.doc);return heading('CHECK / PREVIEW','生成之前，最后核对一次。','先修正缺失项，再确认每种单据的抬头与附加内容。')+`<div class="split" style="grid-template-columns:minmax(250px,.65fr) minmax(380px,1.4fr)"><section><div class="panel"><h2>输出设置</h2><label>使用模板<select onchange="useTemplate(Number(this.value))">${state.templates.map((t,i)=>`<option value="${i}" ${state.selected===t.name?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>预览单据<select onchange="state.doc=this.value;save();render()"><option ${state.doc==='发票'?'selected':''}>发票</option><option ${state.doc==='装箱单'?'selected':''}>装箱单</option></select></label><p class="muted">当前展示抬头与附加条款，货物明细和正式排版将在开发阶段接入。</p></div><div class="panel" style="margin-top:18px"><h2>生成检查 <span class="pill ${list.length?'warn':''}">${list.length?list.length+' 项待处理':'已完成'}</span></h2>${list.map(x=>`<button style="display:flex;width:100%;margin-top:10px;text-align:left" onclick="go('work',${x.step})">${icon('arrow-up-right')}${esc(x.text)}</button>`).join('')||'<p>必填内容完整，基础信息已确认。</p>'}<h3 style="margin-top:24px">${esc(state.doc)}操作要求</h3>${cs.filter(c=>c.type==='操作要求').map(c=>`<p>${esc(c.value)||'待填写'}</p>`).join('')||'<span class="muted">未设置额外操作要求</span>'}</div></section><article class="paperpreview"><div class="watermark">DESIGN PREVIEW / 示例预览</div><h2>${state.doc==='发票'?'COMMERCIAL INVOICE':'PACKING LIST'}</h2><dl><dt>SELLER</dt><dd>${esc(b.seller)||'待填写'}</dd><dt>BUYER</dt><dd>${esc(b.buyer)||'待填写'}</dd><dt>INVOICE NO.</dt><dd>${esc(b.invoice)||'待填写'}</dd><dt>DATE</dt><dd>${esc(b.date)||'—'}</dd><dt>L/C NO.</dt><dd>${esc(b.lc)||'—'}</dd></dl><div style="border-top:1px solid var(--line);margin-top:32px;padding-top:20px"><h3>ADDITIONAL REFERENCES</h3>${cs.filter(c=>c.type!=='操作要求').map(c=>`<p style="color:var(--ink)">${esc(c.name)}: ${esc(c.value)||'<span style="color:var(--amber)">待补充</span>'}</p>`).join('')||'<p>无额外条款</p>'}</div></article></div><div class="bottom"><button onclick="go('work',2)">返回编辑</button><div class="actions"><button onclick="openTemplateDialog()">保存为模板</button><button class="primary" ${list.length?'disabled':''} onclick="downloadPreview()">${icon('download')}下载演示摘要</button></div></div>`;}
function downloadPreview(){if(issues().length){toast('请先完成检查项');return;}const b=state.business;const text=['设计原型演示摘要（非正式单据）',state.doc,b.name,'卖方：'+b.seller,'买方：'+b.buyer,'发票号：'+b.invoice,'信用证号：'+b.lc,...b.clauses.filter(c=>c.scope==='全部单据'||c.scope===state.doc).map(c=>`${c.type==='操作要求'?'[检查清单] ':''}${c.name}：${c.value}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='单据演示摘要.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已下载演示摘要，正式 Word / Excel 导出待开发');}
render();
