const store=require('../../lib/store');const d=require('../../lib/domain');const ui=require('../../lib/ui');const docx=require('../../lib/docx');
Page({data:{business:null,docIndex:0,docNames:['发票','装箱单'],issues:[],document:null,invoiceSelected:true,packingSelected:false,history:[],latestOutput:null,latestOutputs:[],olderOutputs:[],error:'',generating:false,templateName:'内置抬头草稿'},
onShow(){ui.tab(this,2);this.refresh();},
refresh(){try{const b=store.active();if(!b){this.setData({business:null,history:[],latestOutputs:[],olderOutputs:[]});return;}const doc=['invoice','packingList'][this.data.docIndex],s=store.read(),template=b.template&&s.templates.find(t=>t.id===b.template.id&&t.version===b.template.version),selected=b.selectedDocuments||['invoice'];const history=s.generations.filter(g=>g.snapshot.businessId===b.id).map(g=>{const output=g.snapshot.documents&&g.snapshot.documents[0]||{},type=output.documentType||'invoice',refs=g.snapshot.references||{};return {id:g.snapshot.id,path:g.path,date:g.snapshot.generatedAt.slice(0,16).replace('T',' '),docType:type,docName:type==='packingList'?'装箱单':'发票',lcNumber:refs.lcNumber||output.fields?.lcNumber||'',invoiceNumber:refs.invoiceNumber||output.fields?.invoiceNumber||'',stale:g.snapshot.businessRevision!==b.revision};});const latestOutputs=[],olderOutputs=[],seen=new Set();for(const item of history){if(seen.has(item.docType))olderOutputs.push(item);else{latestOutputs.push(item);seen.add(item.docType);}}this.setData({business:b,invoiceSelected:selected.includes('invoice'),packingSelected:selected.includes('packingList'),document:d.projectDocument(b,doc),issues:d.validateBusiness(b,selected).map(x=>({...x,text:ui.issueText(x),step:2})),history,latestOutput:history[0]||null,latestOutputs,olderOutputs,templateName:template?template.name:'内置抬头草稿',error:''});}catch(e){ui.fail(this,e);}},
changeDoc(e){this.setData({docIndex:Number(e.detail.value)});this.refresh();},
toggleDoc(e){try{const b=store.active(),doc=e.currentTarget.dataset.doc,selected=[...(b.selectedDocuments||['invoice'])];if(e.detail.value&&!selected.includes(doc))selected.push(doc);if(!e.detail.value){const index=selected.indexOf(doc);if(index>=0)selected.splice(index,1);}if(!selected.length){ui.notify('请至少选择一份单据');this.refresh();return;}b.selectedDocuments=selected;b.revision++;b.updatedAt=new Date().toISOString();store.update(b);this.refresh();}catch(error){ui.fail(this,error);}},
edit(e){wx.navigateTo({url:'/pages/editor/index?step='+(e.currentTarget.dataset.step??2)});},templates(){wx.switchTab({url:'/pages/templates/index'});},create(){wx.switchTab({url:'/pages/home/index'});},
generate(){if(this.data.generating)return;try{const b=store.active(),docs=b.selectedDocuments||['invoice'];if(d.validateBusiness(b,docs).length){this.refresh();return;}const s=store.read(),template=b.template&&s.templates.find(t=>t.id===b.template.id&&t.version===b.template.version)||{id:'builtin-header',version:1,name:'内置抬头草稿'};const outputs=docs.map(doc=>{const snapshot=d.createGenerationSnapshot(b,template,[doc]);return {snapshot,path:wx.env.USER_DATA_PATH+'/header-'+snapshot.id+'-'+doc+'.docx',data:docx.generate(snapshot.documents[0])};});this.setData({generating:true});let index=0;const finish=()=>{try{store.recordGenerations(outputs.map(({snapshot,path})=>({snapshot,path})));this.refresh();wx.openDocument({filePath:outputs[0].path,fileType:'docx',showMenu:true,fail:e=>ui.fail(this,e)});}catch(e){ui.fail(this,e);}finally{this.setData({generating:false});}};const writeNext=()=>{if(index===outputs.length){finish();return;}const output=outputs[index++];wx.getFileSystemManager().writeFile({filePath:output.path,data:output.data,success:writeNext,fail:e=>{this.setData({generating:false});ui.fail(this,e);}});};writeNext();}catch(e){this.setData({generating:false});ui.fail(this,e);}},
openHistory(e){wx.openDocument({filePath:e.currentTarget.dataset.path,fileType:'docx',showMenu:true,fail:error=>ui.fail(this,error)});},
saveOutput(e){wx.shareFileMessage({filePath:e.currentTarget.dataset.path,fail:error=>{if(!ui.cancel(error))ui.fail(this,error);}});}});
