import fs from 'node:fs';
const source = fs.readFileSync(new URL('../src/domain/documents.mjs', import.meta.url),'utf8');
const names = [...source.matchAll(/export (?:const|function) (\w+)/g)].map(match=>match[1]);
const portable = source.replace('const randomUUID = () => globalThis.crypto.randomUUID();', "let sequence = 0;\nconst randomUUID = () => Date.now().toString(36) + '-' + (++sequence).toString(36) + '-' + Math.random().toString(36).slice(2,12);")
 .replace('structuredClone(value)', 'JSON.parse(JSON.stringify(value))')
 .replace('Object.hasOwn(business.fields, key)', 'Object.prototype.hasOwnProperty.call(business.fields, key)')
 .replace(/input\.(\w+) \?\? (\[[^\]]*\]|'[^']*'|true|false|\{ kind: 'manual' \})/g, '(input.$1 !== undefined ? input.$1 : $2)')
 .replace(/export /g,'');
fs.writeFileSync(new URL('../miniprogram/lib/domain.js', import.meta.url), '// Generated by scripts/sync-domain.mjs; edit src/domain/documents.mjs.\n'+portable+'\nmodule.exports = { '+names.join(', ')+' };\n');
